/// Internal enum tracking the mutation state of a DAT node
#[derive(Debug, Clone, Copy, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
pub enum DatUpdateStatus {
    /// DAT needs to be deleted
    Delete,
    /// DAT is correctly processed
    Correct,
}

bitflags::bitflags! {
    /// Configuration flags applied to a DAT node
    #[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, serde::Serialize, serde::Deserialize)]
    pub struct DatFlags: u8 {
        /// No flags set
        const NONE = 0;
        /// Generated by an automatic folder scan
        const AUTO_ADDED_DIRECTORY = 1;
        /// Override merge rules from settings
        const MERGE_OVERRIDE_DAT = 2;
        /// Override sub-directory grouping from settings
        const MULTI_DAT_OVERRIDE = 4;
        /// Override compression format from settings
        const COMPRESSION_OVERRIDE_DAT = 8;
    }
}

/// Identifiers for standard DAT header fields
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
pub enum DatData {
    /// Identifier string
    Id = 0,
    /// Human readable name
    DatName = 1,
    /// Root path where files are extracted
    DatRootFullName = 2,
    /// Local root directory
    RootDir = 3,
    /// DAT description
    Description = 4,
    /// Classification category
    Category = 5,
    /// DAT Version string
    Version = 6,
    /// Release date
    Date = 7,
    /// Original author
    Author = 8,
    /// Contact email
    Email = 9,
    /// Website URL
    HomePage = 10,
    /// Source URL
    Url = 11,
    /// Intended compression file type
    FileType = 12,
    /// Intended ROM merge type
    MergeType = 13,
    /// Is this a SuperDAT
    SuperDat = 14,
    /// Directory configuration logic
    DirSetup = 15,
    /// Console header configuration
    Header = 16,
    /// Sub-directory logic
    SubDirType = 17,
    /// Target compression level
    Compression = 18,
}

/// A key-value pair storing metadata for a DAT
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct DatMetaData {
    /// The metadata key
    pub id: DatData,
    /// The metadata value
    pub value: String,
}

/// Logical representation of a DAT file within the internal database.
///
/// `RvDat` holds the metadata (Name, Description, Version) and operational flags
/// (e.g. `AutoAddedDirectory`, `MultiDatOverride`) extracted from a `.dat` file.
/// It is usually bound to an `RvFile` representing the root directory of that DAT's games.
///
/// Differences from C#:
/// - The C# version tightly packs `DatData` strings into an array indexed by the enum.
/// - The Rust version stores them dynamically in a `Vec<DatMetaData>` to optimize serialization
///   size, as most DATs only populate a few of the 18 possible metadata fields.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct RvDat {
    /// List of key-value metadata pairs
    pub game_meta_data: Vec<DatMetaData>,
    /// Index in the global DAT list
    #[serde(
        default = "default_dat_index",
        deserialize_with = "crate::rv_file::de_i32_compat"
    )]
    pub dat_index: i32,
    /// Internal processing status
    pub status: DatUpdateStatus,
    /// Timestamp of the underlying `.dat` file
    pub time_stamp: i64,
    /// Operation flags configured for this DAT
    pub dat_flags: DatFlags,
}

fn default_dat_index() -> i32 {
    -1
}

impl RvDat {
    /// Initializes an empty `RvDat` structure
    pub fn new() -> Self {
        Self {
            game_meta_data: Vec::new(),
            dat_index: -1,
            status: DatUpdateStatus::Correct,
            time_stamp: 0,
            dat_flags: DatFlags::empty(),
        }
    }

    /// Sets or updates a metadata string by its `DatData` key
    pub fn set_data(&mut self, id: DatData, value: Option<String>) {
        if let Some(val) = value {
            if val.trim().is_empty() {
                return;
            }
            if let Some(meta) = self.game_meta_data.iter_mut().find(|m| m.id == id) {
                meta.value = val;
            } else {
                self.game_meta_data.push(DatMetaData { id, value: val });
            }
        }
    }

    /// Retrieves a metadata string by its `DatData` key
    pub fn get_data(&self, id: DatData) -> Option<String> {
        self.game_meta_data
            .iter()
            .find(|m| m.id == id)
            .map(|m| m.value.clone())
    }

    /// Checks if a specific `DatFlags` bit is set
    pub fn flag(&self, flag: DatFlags) -> bool {
        self.dat_flags.contains(flag)
    }
}

impl Default for RvDat {
    fn default() -> Self {
        Self::new()
    }
}
