use dat_reader::enums::{FileType, GotStatus, HeaderFileType, ZipStructure};
use crate::rv_file::FileStatus;

/// Data structure representing a physically scanned file or directory.
/// 
/// `ScannedFile` is a temporary object generated by the `Scanner` during a physical disk sweep.
/// It holds the exact metadata (size, hashes, timestamps) pulled directly from the filesystem 
/// or archive stream, which is then compared against the logical `RvFile` tree by `FileScanning`.
/// 
/// Differences from C#:
/// - Maps 1:1 to the C# `RomVault.ScannedFile` class.
#[derive(Clone, Debug)]
pub struct ScannedFile {
    /// The local filename
    pub name: String,
    /// Physical file timestamp
    pub file_mod_time_stamp: i64,
    /// File type enum (e.g. `Zip`, `SevenZip`, `File`)
    pub file_type: FileType,
    /// Current got status of the physical file
    pub got_status: GotStatus,

    /// Inner zip structure validation enum
    pub zip_struct: ZipStructure,
    /// Optional archive comment
    pub comment: String,
    /// Nested child files (if this is a directory or archive)
    pub children: Vec<ScannedFile>,

    /// Raw byte offset into an archive
    pub local_header_offset: Option<u64>,
    /// Whether this file has had its hashes computed yet
    pub deep_scanned: bool,
    /// Validation flags
    pub status_flags: FileStatus,
    /// Archive directory index
    pub index: i32,

    /// Emulation header format
    pub header_file_type: HeaderFileType,
    /// Total byte size
    pub size: Option<u64>,
    /// CRC32 Hash
    pub crc: Option<Vec<u8>>,
    /// SHA1 Hash
    pub sha1: Option<Vec<u8>>,
    /// MD5 Hash
    pub md5: Option<Vec<u8>>,
    /// SHA256 Hash
    pub sha256: Option<Vec<u8>>,

    /// Headerless size
    pub alt_size: Option<u64>,
    /// Headerless CRC32
    pub alt_crc: Option<Vec<u8>>,
    /// Headerless SHA1
    pub alt_sha1: Option<Vec<u8>>,
    /// Headerless MD5
    pub alt_md5: Option<Vec<u8>>,
    /// Headerless SHA256
    pub alt_sha256: Option<Vec<u8>>,

    /// MAME CHD Version
    pub chd_version: Option<u32>,
    /// Temporary search pass tracking flag
    pub search_found: bool,
}

impl ScannedFile {
    fn ascii_lower(byte: u8) -> u8 {
        if byte.is_ascii_uppercase() {
            byte + 0x20
        } else {
            byte
        }
    }

    fn string_compare(a: &str, b: &str) -> i32 {
        match a.cmp(b) {
            std::cmp::Ordering::Less => -1,
            std::cmp::Ordering::Equal => 0,
            std::cmp::Ordering::Greater => 1,
        }
    }

    fn directory_name_compare(a: &str, b: &str) -> i32 {
        Self::string_compare(&a.to_ascii_lowercase(), &b.to_ascii_lowercase())
    }

    fn directory_name_compare_case(a: &str, b: &str) -> i32 {
        let res = Self::directory_name_compare(a, b);
        if res != 0 {
            return res;
        }
        Self::string_compare(a, b)
    }

    fn trrnt_zip_string_compare(a: &str, b: &str) -> i32 {
        let bytes_a = a.as_bytes();
        let bytes_b = b.as_bytes();
        let len = std::cmp::min(bytes_a.len(), bytes_b.len());

        for i in 0..len {
            let ca = Self::ascii_lower(bytes_a[i]);
            let cb = Self::ascii_lower(bytes_b[i]);
            if ca < cb {
                return -1;
            }
            if ca > cb {
                return 1;
            }
        }

        if bytes_a.len() < bytes_b.len() {
            -1
        } else if bytes_a.len() > bytes_b.len() {
            1
        } else {
            0
        }
    }

    fn trrnt_zip_string_compare_case(a: &str, b: &str) -> i32 {
        let res = Self::trrnt_zip_string_compare(a, b);
        if res != 0 {
            return res;
        }
        Self::string_compare(a, b)
    }

    fn split_7zip_filename(filename: &str) -> (&str, &str, &str) {
        let dir_index = filename.rfind('/');
        let (path, name) = if let Some(i) = dir_index {
            (&filename[..i], &filename[i + 1..])
        } else {
            ("", filename)
        };

        let ext_index = name.rfind('.');
        if let Some(i) = ext_index {
            (path, &name[..i], &name[i + 1..])
        } else {
            (path, name, "")
        }
    }

    fn trrnt_7zip_string_compare(a: &str, b: &str) -> i32 {
        let (path_a, name_a, ext_a) = Self::split_7zip_filename(a);
        let (path_b, name_b, ext_b) = Self::split_7zip_filename(b);

        let res = Self::string_compare(ext_a, ext_b);
        if res != 0 {
            return res;
        }
        let res = Self::string_compare(name_a, name_b);
        if res != 0 {
            return res;
        }
        Self::string_compare(path_a, path_b)
    }

    fn list_search(list: &[ScannedFile], needle: &ScannedFile, cmp: fn(&ScannedFile, &ScannedFile) -> i32) -> usize {
        let mut bottom = 0usize;
        let mut top = list.len();
        let mut mid = 0usize;
        let mut res = -1i32;

        while bottom < top && res != 0 {
            mid = (bottom + top) / 2;
            res = cmp(needle, &list[mid]);
            if res < 0 {
                top = mid;
            } else if res > 0 {
                bottom = mid + 1;
            }
        }

        let mut index = mid;
        if res == 0 {
            while index > 0 && cmp(needle, &list[index - 1]) == 0 {
                index -= 1;
            }
        } else if res > 0 {
            index += 1;
        }

        index
    }

    fn compare_name_dir(left: &ScannedFile, right: &ScannedFile) -> i32 {
        Self::directory_name_compare_case(&left.name, &right.name)
    }

    fn compare_name_trrntzip(left: &ScannedFile, right: &ScannedFile) -> i32 {
        Self::trrnt_zip_string_compare_case(&left.name, &right.name)
    }

    fn compare_name_7zip(left: &ScannedFile, right: &ScannedFile) -> i32 {
        Self::trrnt_7zip_string_compare(&left.name, &right.name)
    }

    /// Instantiates a new empty ScannedFile node
    pub fn new(file_type: FileType) -> Self {
        Self {
            name: String::new(),
            file_mod_time_stamp: 0,
            file_type,
            got_status: GotStatus::NotGot,
            zip_struct: ZipStructure::None,
            comment: String::new(),
            children: Vec::new(),
            local_header_offset: None,
            deep_scanned: false,
            status_flags: FileStatus::NONE,
            index: 0,
            header_file_type: HeaderFileType::NOTHING,
            size: None,
            crc: None,
            sha1: None,
            md5: None,
            sha256: None,
            alt_size: None,
            alt_crc: None,
            alt_sha1: None,
            alt_md5: None,
            alt_sha256: None,
            chd_version: None,
            search_found: false,
        }
    }

    /// Determines if this file type is functionally a directory (Zip, 7z, Dir).
    pub fn is_directory(&self) -> bool {
        matches!(self.file_type, FileType::Zip | FileType::SevenZip | FileType::Dir)
    }

    /// Pushes a new child file into this directory's inner list.
    pub fn add(&mut self, child: ScannedFile) {
        self.children.push(child);
    }

    /// Alphabetically sorts the internal child files list.
    pub fn sort(&mut self) {
        let cmp: fn(&ScannedFile, &ScannedFile) -> i32 = match self.file_type {
            FileType::SevenZip => Self::compare_name_7zip,
            FileType::Zip => Self::compare_name_trrntzip,
            FileType::Dir => Self::compare_name_dir,
            _ => return,
        };

        let files = std::mem::take(&mut self.children);
        for file in files {
            let index = Self::list_search(&self.children, &file, cmp);
            self.children.insert(index, file);
        }
    }
}

#[cfg(test)]
#[path = "tests/scanned_file_tests.rs"]
mod tests;
