use dat_reader::enums::{FileType, GotStatus, HeaderFileType, ZipStructure};
use crate::rv_file::FileStatus;

/// Data structure representing a physically scanned file or directory.
/// 
/// `ScannedFile` is a temporary object generated by the `Scanner` during a physical disk sweep.
/// It holds the exact metadata (size, hashes, timestamps) pulled directly from the filesystem 
/// or archive stream, which is then compared against the logical `RvFile` tree by `FileScanning`.
/// 
/// Differences from C#:
/// - Maps 1:1 to the C# `RomVault.ScannedFile` class.
#[derive(Clone, Debug)]
pub struct ScannedFile {
    /// The local filename
    pub name: String,
    /// Physical file timestamp
    pub file_mod_time_stamp: i64,
    /// File type enum (e.g. `Zip`, `SevenZip`, `File`)
    pub file_type: FileType,
    /// Current got status of the physical file
    pub got_status: GotStatus,

    /// Inner zip structure validation enum
    pub zip_struct: ZipStructure,
    /// Optional archive comment
    pub comment: String,
    /// Nested child files (if this is a directory or archive)
    pub children: Vec<ScannedFile>,

    /// Raw byte offset into an archive
    pub local_header_offset: Option<u64>,
    /// Whether this file has had its hashes computed yet
    pub deep_scanned: bool,
    /// Validation flags
    pub status_flags: FileStatus,
    /// Archive directory index
    pub index: i32,

    /// Emulation header format
    pub header_file_type: HeaderFileType,
    /// Total byte size
    pub size: Option<u64>,
    /// CRC32 Hash
    pub crc: Option<Vec<u8>>,
    /// SHA1 Hash
    pub sha1: Option<Vec<u8>>,
    /// MD5 Hash
    pub md5: Option<Vec<u8>>,
    /// SHA256 Hash
    pub sha256: Option<Vec<u8>>,

    /// Headerless size
    pub alt_size: Option<u64>,
    /// Headerless CRC32
    pub alt_crc: Option<Vec<u8>>,
    /// Headerless SHA1
    pub alt_sha1: Option<Vec<u8>>,
    /// Headerless MD5
    pub alt_md5: Option<Vec<u8>>,
    /// Headerless SHA256
    pub alt_sha256: Option<Vec<u8>>,

    /// MAME CHD Version
    pub chd_version: Option<u32>,
    /// Temporary search pass tracking flag
    pub search_found: bool,
}

impl ScannedFile {
    fn compare_names(left: &str, right: &str) -> std::cmp::Ordering {
        #[cfg(windows)]
        {
            left.to_ascii_lowercase().cmp(&right.to_ascii_lowercase())
        }
        #[cfg(not(windows))]
        {
            left.cmp(right)
        }
    }

    /// Instantiates a new empty ScannedFile node
    pub fn new(file_type: FileType) -> Self {
        Self {
            name: String::new(),
            file_mod_time_stamp: 0,
            file_type,
            got_status: GotStatus::NotGot,
            zip_struct: ZipStructure::None,
            comment: String::new(),
            children: if file_type == FileType::Dir || file_type == FileType::Zip || file_type == FileType::SevenZip {
                Vec::new()
            } else {
                Vec::new() // Default empty
            },
            local_header_offset: None,
            deep_scanned: false,
            status_flags: FileStatus::NONE,
            index: 0,
            header_file_type: HeaderFileType::NOTHING,
            size: None,
            crc: None,
            sha1: None,
            md5: None,
            sha256: None,
            alt_size: None,
            alt_crc: None,
            alt_sha1: None,
            alt_md5: None,
            alt_sha256: None,
            chd_version: None,
            search_found: false,
        }
    }

    /// Determines if this file type is functionally a directory (Zip, 7z, Dir).
    pub fn is_directory(&self) -> bool {
        matches!(self.file_type, FileType::Zip | FileType::SevenZip | FileType::Dir)
    }

    /// Pushes a new child file into this directory's inner list.
    pub fn add(&mut self, child: ScannedFile) {
        self.children.push(child);
    }

    /// Alphabetically sorts the internal child files list.
    pub fn sort(&mut self) {
        self.children.sort_by(|a, b| Self::compare_names(&a.name, &b.name));
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_sort_uses_windows_style_case_insensitive_ordering() {
        let mut dir = ScannedFile::new(FileType::Dir);
        let mut upper = ScannedFile::new(FileType::File);
        upper.name = "B.bin".to_string();
        let mut lower = ScannedFile::new(FileType::File);
        lower.name = "a.bin".to_string();
        dir.children.push(upper);
        dir.children.push(lower);

        dir.sort();

        assert_eq!(dir.children[0].name, "a.bin");
        assert_eq!(dir.children[1].name, "B.bin");
    }
}
